"""Configuration for UEBA baseline acceptance fixtures."""

from dataclasses import dataclass, field
from datetime import datetime
import os
from pathlib import Path


def _env_clickhouse_port() -> int:
    raw = os.getenv("CLICKHOUSE_PORT", "8123")
    try:
        port = int(raw)
    except ValueError as exc:
        raise ValueError(
            f"CLICKHOUSE_PORT 必须为正整数，当前值: {raw!r}"
        ) from exc
    if port <= 0 or port > 65535:
        raise ValueError(
            f"CLICKHOUSE_PORT 必须为 1..65535 的正整数，当前值: {port}"
        )
    return port


@dataclass(slots=True)
class AcceptanceConfig:
    """Config for the offline UEBA baseline acceptance fixture tool."""

    clickhouse_host: str = field(
        default_factory=lambda: os.getenv("CLICKHOUSE_HOST", "localhost")
    )
    clickhouse_port: int = field(default_factory=_env_clickhouse_port)
    clickhouse_user: str = field(
        default_factory=lambda: os.getenv(
            "CLICKHOUSE_USERNAME",
            os.getenv("CLICKHOUSE_USER", "default"),
        )
    )
    clickhouse_password: str = field(
        default_factory=lambda: os.getenv("CLICKHOUSE_PASSWORD", "")
    )
    clickhouse_database: str = field(
        default_factory=lambda: os.getenv("CLICKHOUSE_DATABASE", "log_analysis")
    )

    output_dir: Path = Path(".tox/ueba_baseline_acceptance")

    fixture_id: str = "ueba_fixture_v2_monthly_seed_42"
    seed: int = 42

    start_time: str = "2026-05-01 00:00:00"
    end_time: str = "2026-07-01 00:00:00"
    log_type: str = "vpn"
    model_version: str = "ueba_baseline_fixture_v2_monthly"
    min_sample_count: int = 20

    stable_user_count: int = 10
    multi_location_user_count: int = 4
    high_failure_user_count: int = 3
    offhour_user_count: int = 3
    ip_long_tail_user_count: int = 2
    logs_per_main_user: int = 1500

    clean_before_load: bool = True
    clickhouse_batch_size: int = 1000
    dump_logs_jsonl: bool = False
    validation_float_tolerance: float = 0.0001
    validation_common_min_ratio: float = 0.1

    @property
    def edge_user_sample_counts(self) -> tuple[int, int, int, int]:
        """Return fixed boundary-user sample counts."""
        return (5, 19, 20, 21)

    # validation acceptance 专用 baseline 用户数
    validation_baseline_user_count: int = 2

    @property
    def expected_user_count(self) -> int:
        """Return the number of fixture users generated by default."""
        return (
            self.stable_user_count
            + self.multi_location_user_count
            + self.high_failure_user_count
            + self.offhour_user_count
            + self.ip_long_tail_user_count
            + len(self.edge_user_sample_counts)
            + self.validation_baseline_user_count
        )

    @property
    def fixture_usernames(self) -> list[str]:
        """Return the exact list of fixture usernames used for destructive cleanup scoping."""
        users: list[str] = []
        for i in range(1, self.stable_user_count + 1):
            users.append(f"fixture_user_stable_{i:04d}")
        for i in range(1, self.multi_location_user_count + 1):
            users.append(f"fixture_user_multi_{i:04d}")
        for i in range(1, self.high_failure_user_count + 1):
            users.append(f"fixture_user_failed_{i:04d}")
        for i in range(1, self.offhour_user_count + 1):
            users.append(f"fixture_user_offhour_{i:04d}")
        for i in range(1, self.ip_long_tail_user_count + 1):
            users.append(f"fixture_user_iptail_{i:04d}")
        for count in self.edge_user_sample_counts:
            users.append(f"fixture_user_edge_{count:04d}")
        users.append("fixture_user_validation_normal")
        users.append("fixture_user_validation_combo")
        return users

    @property
    def total_expected_logs(self) -> int:
        """Return total fixture log rows implied by this config."""
        main_user_count = (
            self.stable_user_count
            + self.multi_location_user_count
            + self.high_failure_user_count
            + self.offhour_user_count
            + self.ip_long_tail_user_count
            + self.validation_baseline_user_count
        )
        months = max(1, _month_count(self.start_time, self.end_time))
        return months * (main_user_count * self.logs_per_main_user + sum(self.edge_user_sample_counts))


def _month_count(start_time: str, end_time: str) -> int:
    """Return the number of calendar months touched by a half-open fixture window."""
    start = datetime.strptime(start_time, "%Y-%m-%d %H:%M:%S")
    end = datetime.strptime(end_time, "%Y-%m-%d %H:%M:%S")
    if start >= end:
        return 0
    return (end.year - start.year) * 12 + end.month - start.month


__all__ = ["AcceptanceConfig"]
